/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button2_click1(GButton source, GEvent event) { //_CODE_:pause:371865:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  paused = !paused;
} //_CODE_:pause:371865:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:543376:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  reset();
} //_CODE_:button3:543376:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:rad:754994:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
  radius = source.getValueF();
} //_CODE_:rad:754994:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  pause = new GButton(this, 1, 1, 80, 30);
  pause.setText("Pause");
  pause.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 1, 31, 80, 30);
  button3.setText("Reset");
  button3.addEventHandler(this, "button3_click1");
  rad = new GSlider(this, 3, 62, 100, 40, 10.0);
  rad.setLimits(20.0, 5.0, 40.0);
  rad.setNumberFormat(G4P.DECIMAL, 2);
  rad.setOpaque(false);
  rad.addEventHandler(this, "slider1_change1");
}

// Variable declarations 
// autogenerated do not edit
GButton pause; 
GButton button3; 
GSlider rad; 
