/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:speed:462861:
  println("speed - GSlider >> GEvent." + event + " @ " + millis());
  maxspeed = source.getValueF();
} //_CODE_:speed:462861:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  speed = new GSlider(this, -1, 14, 100, 40, 10.0);
  speed.setLimits(5.0, 0.0, 10.0);
  speed.setNumberFormat(G4P.DECIMAL, 2);
  speed.setOpaque(false);
  speed.addEventHandler(this, "slider1_change1");
  Speed = new GLabel(this, -20, -2, 80, 20);
  Speed.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Speed.setText("Speed");
  Speed.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GSlider speed; 
GLabel Speed; 
